# Musical test: brain and Otello!

Drinking song, transformation of musical sequences, and mental states

In [19]:
# Matrices: already computed with Omar's program, the Max MSP version of my code in C for the musical matrices

In [2]:
import numpy as np

In [3]:
sequenceA = np.array([[0.06, 0.04, 0.07, 0.08], [0.10, 0.10, 0.11, 0.07], [0.06, 0.03, 0.04, 0.03],[0.04, 0.10, 0.04, 0.03]])

sequenceB = np.array([[0.09, 0.09, 0.06, 0.09], [0.09, 0.06, 0.03, 0.09], [0.09, 0.06, 0.03, 0.03], [0.00, 0.06, 0.06, 0.06]])

sequenceC = np.array([[0.10, 0.10, 0.19, 0.05], [0.10, 0.00, 0.10, 0.10], [0.00, 0.00, 0.00, 0.00], [0.05, 0.10, 0.05, 0.10]])

sequenceD = np.array([[0.04, 0.08, 0.04, 0.08], [0.08, 0.12, 0.08, 0.12], [0.00, 0.08, 0.00, 0.08], [0.04, 0.04, 0.04, 0.04]])

In [4]:
print(sequenceA)

[[0.06 0.04 0.07 0.08]
 [0.1  0.1  0.11 0.07]
 [0.06 0.03 0.04 0.03]
 [0.04 0.1  0.04 0.03]]


In [5]:
# Help from Chat

In [6]:
from scipy.linalg import lstsq

def compute_evolution_operator(matrices):
    """
    Computes the best linear operator D(t) such that D(t) A(t) ≈ A(t+1)
    using least squares regression.
    
    :param matrices: List of numpy arrays [A(0), A(1), A(2), A(3)]
    :return: List of evolution operators [D(1), D(2), D(3)]
    """
    operators = []
    for t in range(len(matrices) - 1):
        A_t = matrices[t]
        A_next = matrices[t + 1]
        
        # Solve D @ A_t ≈ A_next using least squares
        D_t, _, _, _ = lstsq(A_t.T, A_next.T)  # Solving A_t^T @ D^T = A_next^T
        D_t = D_t.T  # Transpose back to get D
        
        operators.append(D_t)
    
    return operators

# Example usage
#A0 = np.random.rand(3, 3)
#A1 = np.random.rand(3, 3)
#A2 = np.random.rand(3, 3)
#A3 = np.random.rand(3, 3)

A0 = sequenceA
A1 = sequenceB
A2 = sequenceC
A3 = sequenceD

matrices = [A0, A1, A2, A3]
D_operators = compute_evolution_operator(matrices)

for i, D in enumerate(D_operators):
    print(f"D({i+1}):\n", D)


D(1):
 [[ 1.125      -1.125       1.5         1.125     ]
 [ 1.48575949 -2.13132911  2.67721519  1.33386076]
 [-0.10917722 -0.84018987  2.52531646  0.72626582]
 [ 0.87341772  0.72151899 -2.20253165  0.18987342]]
D(2):
 [[ 0.75438596 -1.73684211  1.87719298  1.36842105]
 [ 0.30075188  0.90225564 -0.32581454  0.02506266]
 [ 0.          0.          0.          0.        ]
 [ 0.40100251  0.36967419 -0.1566416   0.58897243]]
D(3):
 [[-1.48821656e-16  0.00000000e+00  0.00000000e+00  8.00000000e-01]
 [ 1.03156959e-01  9.47976879e-02  0.00000000e+00  1.08243664e+00]
 [-2.06313917e-01 -1.89595376e-01  0.00000000e+00  1.03512672e+00]
 [ 1.03156959e-01  9.47976879e-02  0.00000000e+00  2.82436639e-01]]


In [9]:
D1 = [[ 1.125,  -1.125,       1.5,         1.125,     ],
 [ 1.48575949, -2.13132911,  2.67721519,  1.33386076],
 [-0.10917722, -0.84018987,  2.52531646,  0.72626582],
 [ 0.87341772,  0.72151899, -2.20253165,  0.18987342]]

In [11]:
test1 = D1@sequenceA
print(test1)

[[ 9.00000000e-02  9.00000000e-02  6.00000000e-02  9.00000000e-02]
 [ 9.00000002e-02  6.00000003e-02  3.00000002e-02  9.00000000e-02]
 [ 9.00000002e-02  6.00000000e-02  3.00000001e-02  2.99999999e-02]
 [-3.27665110e-18  6.00000003e-02  6.00000001e-02  6.00000000e-02]]


In [13]:
sequenceB = np.array([[0.09, 0.09, 0.06, 0.09], [0.09, 0.06, 0.03, 0.09], [0.09, 0.06, 0.03, 0.03], [0.00, 0.06, 0.06, 0.06]])
print(sequenceB)

[[0.09 0.09 0.06 0.09]
 [0.09 0.06 0.03 0.09]
 [0.09 0.06 0.03 0.03]
 [0.   0.06 0.06 0.06]]


In [14]:
import numpy as np
from scipy.linalg import lstsq
from scipy.stats import linregress

def compute_evolution_operator(matrices):
    """
    Computes the best linear operator D(t) such that D(t) A(t) ≈ A(t+1)
    using least squares regression.
    
    :param matrices: List of numpy arrays [A(0), A(1), A(2), A(3)]
    :return: List of evolution operators [D(1), D(2), D(3)]
    """
    operators = []
    for t in range(len(matrices) - 1):
        A_t = matrices[t]
        A_next = matrices[t + 1]
        
        # Solve D @ A_t ≈ A_next using least squares
        D_t, _, _, _ = lstsq(A_t.T, A_next.T)  # Solving A_t^T @ D^T = A_next^T
        D_t = D_t.T  # Transpose back to get D
        operators.append(D_t)
    
    return operators

def estimate_D_t_linear(operators):
    """
    Estimates D(t) as a function of time using linear regression on each matrix element.
    
    :param operators: List of evolution operators [D(1), D(2), D(3)]
    :return: String representations of functions for each element of D(t)
    """
    operators = np.array(operators)
    T, M, N = operators.shape  # Number of time steps and matrix dimensions
    time_steps = np.arange(1, T + 1)
    function_expressions = np.empty((M, N), dtype=object)
    
    for i in range(M):
        for j in range(N):
            y_data = operators[:, i, j]
            slope, intercept, _, _, _ = linregress(time_steps, y_data)
            function_expressions[i, j] = f"{slope:.4f} * t + {intercept:.4f}"
    
    return function_expressions

# Example usage
A0 = np.array([[0.06, 0.04, 0.07, 0.08], [0.10, 0.10, 0.11, 0.07], [0.06, 0.03, 0.04, 0.03], [0.04, 0.10, 0.04, 0.03]])
A1 = np.array([[0.09, 0.09, 0.06, 0.09], [0.09, 0.06, 0.03, 0.09], [0.09, 0.06, 0.03, 0.03], [0.00, 0.06, 0.06, 0.06]])
A2 = np.array([[0.10, 0.10, 0.19, 0.05], [0.10, 0.00, 0.10, 0.10], [0.00, 0.00, 0.00, 0.00], [0.05, 0.10, 0.05, 0.10]])
A3 = np.array([[0.04, 0.08, 0.04, 0.08], [0.08, 0.12, 0.08, 0.12], [0.00, 0.08, 0.00, 0.08], [0.04, 0.04, 0.04, 0.04]])

matrices = [A0, A1, A2, A3]
D_operators = compute_evolution_operator(matrices)
function_expressions = estimate_D_t_linear(D_operators)

for i, D in enumerate(D_operators):
    print(f"D({i+1}):\n", D)

print("Explicit functions for D(t):\n", function_expressions)


D(1):
 [[ 1.125      -1.125       1.5         1.125     ]
 [ 1.48575949 -2.13132911  2.67721519  1.33386076]
 [-0.10917722 -0.84018987  2.52531646  0.72626582]
 [ 0.87341772  0.72151899 -2.20253165  0.18987342]]
D(2):
 [[ 0.75438596 -1.73684211  1.87719298  1.36842105]
 [ 0.30075188  0.90225564 -0.32581454  0.02506266]
 [ 0.          0.          0.          0.        ]
 [ 0.40100251  0.36967419 -0.1566416   0.58897243]]
D(3):
 [[-1.48821656e-16  0.00000000e+00  0.00000000e+00  8.00000000e-01]
 [ 1.03156959e-01  9.47976879e-02  0.00000000e+00  1.08243664e+00]
 [-2.06313917e-01 -1.89595376e-01  0.00000000e+00  1.03512672e+00]
 [ 1.03156959e-01  9.47976879e-02  0.00000000e+00  2.82436639e-01]]
Explicit functions for D(t):
 [['-0.5625 * t + 1.7515' '0.5625 * t + -2.0789' '-0.7500 * t + 2.6257'
  '-0.1625 * t + 1.4228']
 ['-0.6913 * t + 2.0125' '1.1131 * t + -2.6042' '-1.3386 * t + 3.4610'
  '-0.1257 * t + 1.0652']
 ['-0.0486 * t + -0.0080' '0.3253 * t + -0.9939' '-1.2627 * t + 3.3671'
  '0

In [26]:
t = 1
#t = 2

Dt =  [[-0.5625 * t + 1.7515, 0.5625 * t + -2.0789, -0.7500 * t + 2.6257,
  -0.1625 * t + 1.4228],
 [-0.6913 * t + 2.0125, 1.1131 * t + -2.6042, -1.3386 * t + 3.4610,
  -0.1257 * t + 1.0652],
 [-0.0486 * t + -0.0080, 0.3253 * t + -0.9939, -1.2627 * t + 3.3671,
  0.1544 * t + 0.2783],
 [-0.3851 * t + 1.2295, -0.3134 * t + 1.0221, 1.1013 * t + -2.9889,
  0.0463 * t + 0.2612]]

#print(Dt)

testA = Dt@sequenceA
print(testA)

#testB = Dt@sequenceB
#print(testB)

[[0.082654 0.078221 0.041866 0.083052]
 [0.095086 0.06136  0.050939 0.093176]
 [0.073316 0.037278 0.023976 0.024783]
 [0.020578 0.078768 0.073861 0.069758]]


In [27]:
print(sequenceB)
#print(sequenceC)

[[0.09 0.09 0.06 0.09]
 [0.09 0.06 0.03 0.09]
 [0.09 0.06 0.03 0.03]
 [0.   0.06 0.06 0.06]]
